services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - 8080:80
            - 8443:443
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=$APP_KEY # How to generate an app key: https://speedtest-tracker.dev/
            - APP_URL=http://localhost
            - DB_CONNECTION=sqlite
            - APP_DEBUG=true
            # - SPEEDTEST_SCHEDULE= # optional: schedule a speedtest with an cronjob https://crontab.guru
        volumes:
            - $CONFIG_PATH:/config
            - $SSL_KEYS_PATH:/config/keys
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped